SELECT
GLCO2A AS company_group,
CONO2A AS company_number,
APPL2A AS application,
TREF2A AS contact_reference,
TLNO2A AS note_line,
RTRIM(TRIM(TLIN2A)) AS note_text,
HEX(HASH(VARCHAR(COALESCE(RTRIM(TRIM(TLIN2A)),'') ))) AS row_hash,
CURRENT_TIMESTAMP AS load_ts
FROM EDUT1F3.T1P2A
WHERE GLCO2A='GK'
AND CONO2A='GK'
AND APPL2A='SL'
AND TXTT2A='C'