SELECT
    GLCO2A AS COMPANY_GROUP,
    CONO2A AS COMPANY_NUMBER,
    APPL2A AS APPLICATION,
    TREF2A AS CONTACT_REFERENCE,
    TLNO2A AS NOTE_LINE_NUMBER,
    TLIN2A AS NOTE_TEXT

FROM EDUT1F3.T1P2A

WHERE
    GLCO2A = 'GK'
AND CONO2A = 'GK'
AND APPL2A = 'SL'