WITH SLP05_DEDUP AS (
SELECT
S.*,
ROW_NUMBER() OVER (
PARTITION BY S.CONO05,S.CUSN05,S.DSEQ05
ORDER BY
CASE WHEN S.RSTS05='R' THEN 1 ELSE 0 END,
S.ACDT05 DESC
) AS RN
FROM EDUT1F3.SLP05 S
WHERE S.CONO05='GK'
AND S.DSEQ05='000'
),
DeliveryFiltered AS (
SELECT *
FROM EDUT2F3.TPP24
WHERE COALESCE(DAY124,'')<>'' 
OR COALESCE(DAY224,'')<>'' 
OR COALESCE(DAY324,'')<>'' 
OR COALESCE(DAY424,'')<>'' 
OR COALESCE(DAY524,'')<>'' 
OR COALESCE(DAY624,'')<>'' 
OR COALESCE(DAY724,'')<>''
),
DeliveryAgg AS (
SELECT
CONO24,
CUSN24,
DSEQ24,
MIN(TRIM(DFRT24)) AS DELIVERY_ROUTE,
MIN(TRIM(TPCN24)) AS TRANSPORT_CENTRE,
MAX(DAY124) AS DELIVERY_MONDAY,
MAX(DAY224) AS DELIVERY_TUESDAY,
MAX(DAY324) AS DELIVERY_WEDNESDAY,
MAX(DAY424) AS DELIVERY_THURSDAY,
MAX(DAY524) AS DELIVERY_FRIDAY,
MAX(DAY624) AS DELIVERY_SATURDAY,
MAX(DAY724) AS DELIVERY_SUNDAY
FROM DeliveryFiltered
GROUP BY CONO24,CUSN24,DSEQ24
),
OEP20U_AGG AS (
SELECT
CONO20,
CUSN20,
DSEQ20,
MAX(OECS20) AS OE_CUSTOMER,
MAX(EQCS20) AS EQ_CUSTOMER,
MAX(CSCS20) AS CS_CUSTOMER
FROM EDUMODS3.OEP20U
WHERE CONO20='GK'
GROUP BY CONO20,CUSN20,DSEQ20
),
BASE_RESULT AS (
SELECT
S.CONO05 AS COMPANY_NUMBER,
TRIM(S.CUSN05) AS CUSTOMER_ACCOUNT,
TRIM(S.DSEQ05) AS DELIVERY_SEQUENCE,
COALESCE(S.RSTS05,'') AS CUSTOMER_STATUS,
CASE
WHEN S.RSTS05='S' THEN 'Suspended'
WHEN S.RSTS05='R' THEN 'Closed'
WHEN S.RSTS05='L' THEN 'Legal'
WHEN COALESCE(S.RSTS05,'')='' THEN 'Active'
ELSE 'Closed'
END AS CUSTOMER_STATUS_DESC,
TRIM(S.CNAM05) AS CUSTOMER_NAME,
TRIM(S.CAD105) AS ADDRESS_LINE_1,
TRIM(S.CAD205) AS ADDRESS_LINE_2,
TRIM(S.CAD305) AS ADDRESS_LINE_3,
TRIM(S.CAD405) AS ADDRESS_LINE_4,
TRIM(S.CAD505) AS ADDRESS_LINE_5,
TRIM(S.PCD105) AS POST_CODE_PART1,
TRIM(S.PCD205) AS POST_CODE_PART2,
TRIM(S.PTRM05) AS PAYMENT_TERMS_CODE,
TRIM(S.CGP105) AS SECURITISED_CODE,
TRIM(S.CGP305) AS SEGMENT_TOP_LEVEL,
TRIM(S.CGP405) AS SEGMENT_BOTTOM_LEVEL,
TRIM(S.SLMN05) AS SDM_CODE,
TRIM(S.STAD05) AS STATEMENT_ADDRESS_CODE,
TRIM(S.INCD05) AS INVOICE_ADDRESS_CODE,
TRIM(S.PHON05) AS CUSTOMER_TELEPHONE,
TRIM(S.SPIN05) AS SPECIAL_INSTRUCTIONS,
CASE
WHEN S.ACDT05=0 THEN NULL
ELSE DATE(
CASE WHEN SUBSTR(DIGITS(S.ACDT05),1,1)='0'
THEN '19' CONCAT SUBSTR(DIGITS(S.ACDT05),2,2)
ELSE '20' CONCAT SUBSTR(DIGITS(S.ACDT05),2,2)
END CONCAT '-' CONCAT SUBSTR(DIGITS(S.ACDT05),4,2)
CONCAT '-' CONCAT SUBSTR(DIGITS(S.ACDT05),6,2)
)
END AS DATE_ACCOUNT_OPENED,
TRIM(S.WURL05) AS WEBSITE_URL,
TRIM(S.PYCT05) AS PRIMARY_CONTACT,
TRIM(O.DGRP20) AS CUSTOMER_PRICING,
TRIM(O.DISC20) AS PRICE_CODE,
TRIM(O.DIVN20) AS BUSINESS_UNIT_CODE,
TRIM(O.SDIV20) AS TRADE_CHANNEL_CODE,
TRIM(O.REGN20) AS TRADING_STATUS,
TRIM(O.CCLS20) AS CUSTOMER_CLASS,
O.LEAD20 AS DELIVERY_LEAD_TIME,
O.PDRQ20 AS PROOF_OF_DELIVERY_REQ,
O.AINF20 AS INVOICE_FLAG,
TRIM(O.OUTC20) AS OUTLET_CODE,
S.CRLM05 AS CREDIT_LIMIT,
TRIM(S.CRLC05) AS CREDIT_LIMIT_CODE,
TRIM(S.CRSP05) AS CREDIT_CONTROLLER,
S.DDCL05 AS DEBT_DAYS_CREDIT_LIMIT,
TRIM(S.PAYM05) AS PAYMENT_METHOD,
T.TRANSPORT_CENTRE,
T.DELIVERY_ROUTE,
T.DELIVERY_MONDAY,
T.DELIVERY_TUESDAY,
T.DELIVERY_WEDNESDAY,
T.DELIVERY_THURSDAY,
T.DELIVERY_FRIDAY,
T.DELIVERY_SATURDAY,
T.DELIVERY_SUNDAY,
TRIM(S.GCTX05) AS GENERAL_LEDGER_DEBTORS_CONTROL_ACCOUNT_EXTENSION,
TRIM(S.PTTP05) AS PAYMENT_TERMS_TYPE,
S.PTPR05 AS PAYMENT_TERMS_TERMS_DAYS,
S.PTTD05 AS PAYMENT_TERMS_PERIODIC_RANGE,
TRIM(S.CORC05) AS COMPANY_REGISTRATION_CODE,
U.OE_CUSTOMER,
U.EQ_CUSTOMER,
U.CS_CUSTOMER
FROM SLP05_DEDUP S
INNER JOIN EDUT2F3.OEP20 O
ON S.CONO05=O.CONO20
AND S.CUSN05=O.CUSN20
AND S.DSEQ05=O.DSEQ20
LEFT JOIN DeliveryAgg T
ON S.CONO05=T.CONO24
AND S.CUSN05=T.CUSN24
AND S.DSEQ05=T.DSEQ24
LEFT JOIN OEP20U_AGG U
ON S.CONO05=U.CONO20
AND S.CUSN05=U.CUSN20
AND S.DSEQ05=U.DSEQ20
WHERE S.RN=1
AND O.SDIV20 IN ('3','14','15','29','31','33','41','42','44','48','49','53','54','71','72','73','75','76')
),
FINAL_DEDUP AS (
SELECT
B.*,
ROW_NUMBER() OVER (
PARTITION BY B.COMPANY_NUMBER,B.CUSTOMER_ACCOUNT,B.DELIVERY_SEQUENCE
ORDER BY B.CUSTOMER_ACCOUNT
) AS RN2
FROM BASE_RESULT B
)
SELECT
F.*,
HEX(
HASH(
VARCHAR(
COALESCE(F.CUSTOMER_STATUS,'') ||
COALESCE(F.CUSTOMER_STATUS_DESC,'') ||
COALESCE(F.CUSTOMER_NAME,'') ||
COALESCE(F.ADDRESS_LINE_1,'') ||
COALESCE(F.ADDRESS_LINE_2,'') ||
COALESCE(F.ADDRESS_LINE_3,'') ||
COALESCE(F.ADDRESS_LINE_4,'') ||
COALESCE(F.ADDRESS_LINE_5,'') ||
COALESCE(F.POST_CODE_PART1,'') ||
COALESCE(F.POST_CODE_PART2,'') ||
COALESCE(F.PAYMENT_TERMS_CODE,'') ||
COALESCE(F.SECURITISED_CODE,'') ||
COALESCE(F.SEGMENT_TOP_LEVEL,'') ||
COALESCE(F.SEGMENT_BOTTOM_LEVEL,'') ||
COALESCE(F.SDM_CODE,'') ||
COALESCE(F.STATEMENT_ADDRESS_CODE,'') ||
COALESCE(F.INVOICE_ADDRESS_CODE,'') ||
COALESCE(F.CUSTOMER_TELEPHONE,'') ||
COALESCE(F.SPECIAL_INSTRUCTIONS,'') ||
COALESCE(CHAR(F.DATE_ACCOUNT_OPENED),'') ||
COALESCE(F.WEBSITE_URL,'') ||
COALESCE(F.PRIMARY_CONTACT,'') ||
COALESCE(F.CUSTOMER_PRICING,'') ||
COALESCE(F.PRICE_CODE,'') ||
COALESCE(F.BUSINESS_UNIT_CODE,'') ||
COALESCE(F.TRADE_CHANNEL_CODE,'') ||
COALESCE(F.TRADING_STATUS,'') ||
COALESCE(F.CUSTOMER_CLASS,'') ||
COALESCE(CHAR(F.DELIVERY_LEAD_TIME),'') ||
COALESCE(CHAR(F.PROOF_OF_DELIVERY_REQ),'') ||
COALESCE(CHAR(F.INVOICE_FLAG),'') ||
COALESCE(F.OUTLET_CODE,'') ||
COALESCE(CHAR(F.CREDIT_LIMIT),'') ||
COALESCE(F.CREDIT_LIMIT_CODE,'') ||
COALESCE(F.CREDIT_CONTROLLER,'') ||
COALESCE(CHAR(F.DEBT_DAYS_CREDIT_LIMIT),'') ||
COALESCE(F.PAYMENT_METHOD,'') ||
COALESCE(F.TRANSPORT_CENTRE,'') ||
COALESCE(F.DELIVERY_ROUTE,'') ||
COALESCE(CHAR(F.DELIVERY_MONDAY),'') ||
COALESCE(CHAR(F.DELIVERY_TUESDAY),'') ||
COALESCE(CHAR(F.DELIVERY_WEDNESDAY),'') ||
COALESCE(CHAR(F.DELIVERY_THURSDAY),'') ||
COALESCE(CHAR(F.DELIVERY_FRIDAY),'') ||
COALESCE(CHAR(F.DELIVERY_SATURDAY),'') ||
COALESCE(CHAR(F.DELIVERY_SUNDAY),'') ||
COALESCE(F.GENERAL_LEDGER_DEBTORS_CONTROL_ACCOUNT_EXTENSION,'') ||
COALESCE(F.PAYMENT_TERMS_TYPE,'') ||
COALESCE(CHAR(F.PAYMENT_TERMS_TERMS_DAYS),'') ||
COALESCE(CHAR(F.PAYMENT_TERMS_PERIODIC_RANGE),'') ||
COALESCE(F.COMPANY_REGISTRATION_CODE,'') ||
COALESCE(F.OE_CUSTOMER,'') ||
COALESCE(F.EQ_CUSTOMER,'') ||
COALESCE(F.CS_CUSTOMER,'')
)
)
) AS ROW_HASH,
CURRENT_TIMESTAMP AS LOAD_TS
FROM FINAL_DEDUP F
WHERE F.RN2 = 1;
