USE [CRMIntegration]
GO

/****** Object:  Table [dbo].[CRM_Customer_Current]    Script Date: 08/03/2026 14:24:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CRM_Customer_Current](
	[COMPANY_NUMBER] [varchar](5) NOT NULL,
	[CUSTOMER_ACCOUNT] [varchar](20) NOT NULL,
	[DELIVERY_SEQUENCE] [varchar](10) NOT NULL,
	[CUSTOMER_STATUS] [varchar](1) NULL,
	[CUSTOMER_STATUS_DESC] [varchar](20) NULL,
	[CUSTOMER_NAME] [varchar](100) NULL,
	[ADDRESS_LINE_1] [varchar](100) NULL,
	[ADDRESS_LINE_2] [varchar](100) NULL,
	[ADDRESS_LINE_3] [varchar](100) NULL,
	[ADDRESS_LINE_4] [varchar](100) NULL,
	[ADDRESS_LINE_5] [varchar](100) NULL,
	[POST_CODE_PART1] [varchar](10) NULL,
	[POST_CODE_PART2] [varchar](10) NULL,
	[PAYMENT_TERMS_CODE] [varchar](10) NULL,
	[SECURITISED_CODE] [varchar](10) NULL,
	[SEGMENT_TOP_LEVEL] [varchar](50) NULL,
	[SEGMENT_BOTTOM_LEVEL] [varchar](50) NULL,
	[SDM_CODE] [varchar](20) NULL,
	[STATEMENT_ADDRESS_CODE] [varchar](20) NULL,
	[INVOICE_ADDRESS_CODE] [varchar](20) NULL,
	[CUSTOMER_TELEPHONE] [varchar](50) NULL,
	[SPECIAL_INSTRUCTIONS] [varchar](200) NULL,
	[DATE_ACCOUNT_OPENED] [date] NULL,
	[WEBSITE_URL] [varchar](200) NULL,
	[PRIMARY_CONTACT] [varchar](50) NULL,
	[CUSTOMER_PRICING] [varchar](20) NULL,
	[PRICE_CODE] [varchar](20) NULL,
	[BUSINESS_UNIT_CODE] [varchar](20) NULL,
	[TRADE_CHANNEL_CODE] [varchar](20) NULL,
	[TRADING_STATUS] [varchar](20) NULL,
	[CUSTOMER_CLASS] [varchar](20) NULL,
	[DELIVERY_LEAD_TIME] [int] NULL,
	[PROOF_OF_DELIVERY_REQ] [varchar](5) NULL,
	[INVOICE_FLAG] [varchar](5) NULL,
	[OUTLET_CODE] [varchar](20) NULL,
	[CREDIT_LIMIT] [decimal](15, 2) NULL,
	[CREDIT_LIMIT_CODE] [varchar](10) NULL,
	[CREDIT_CONTROLLER] [varchar](50) NULL,
	[DEBT_DAYS_CREDIT_LIMIT] [int] NULL,
	[PAYMENT_METHOD] [varchar](20) NULL,
	[TRANSPORT_CENTRE] [varchar](50) NULL,
	[DELIVERY_ROUTE] [varchar](50) NULL,
	[DELIVERY_MONDAY] [varchar](5) NULL,
	[DELIVERY_TUESDAY] [varchar](5) NULL,
	[DELIVERY_WEDNESDAY] [varchar](5) NULL,
	[DELIVERY_THURSDAY] [varchar](5) NULL,
	[DELIVERY_FRIDAY] [varchar](5) NULL,
	[DELIVERY_SATURDAY] [varchar](5) NULL,
	[DELIVERY_SUNDAY] [varchar](5) NULL,
	[GENERAL_LEDGER_DEBTORS_CONTROL_ACCOUNT_EXTENSION] [varchar](50) NULL,
	[PAYMENT_TERMS_TYPE] [varchar](5) NULL,
	[PAYMENT_TERMS_TERMS_DAYS] [int] NULL,
	[PAYMENT_TERMS_PERIODIC_RANGE] [int] NULL,
	[COMPANY_REGISTRATION_CODE] [varchar](50) NULL,
	[OE_CUSTOMER] [varchar](5) NULL,
	[EQ_CUSTOMER] [varchar](5) NULL,
	[CS_CUSTOMER] [varchar](5) NULL,
	[ROW_HASH] [char](32) NULL,
	[LOAD_TS] [datetime2](3) NULL DEFAULT GETDATE(),
 CONSTRAINT [PK_CRM_Customer_Current] PRIMARY KEY CLUSTERED 
(
	[COMPANY_NUMBER] ASC,
	[CUSTOMER_ACCOUNT] ASC,
	[DELIVERY_SEQUENCE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


