SELECT
    T1.CONO1A AS COMPANY_NUMBER,
    RTRIM(TRIM(T1.TPAC1A)) AS CUSTOMER_ACCOUNT,
    RTRIM(TRIM(T1.DSEQ1A)) AS DELIVERY_SEQUENCE,
    RTRIM(TRIM(T1.CTCT1A)) AS CONTACT_TYPE,
    T1.CTNU1A AS CONTACT_NUMBER,

    RTRIM(TRIM(T1.CNTN1A)) AS CONTACT_NAME,
    RTRIM(TRIM(T1.CNJT1A)) AS JOB_TITLE,
    RTRIM(TRIM(T1.CRNM1A)) AS CORRESPONDENCE_NAME,

    RTRIM(TRIM(T1.HMNB1A)) AS PHONE_HOME,
    RTRIM(TRIM(T1.PFNB1A)) AS PHONE_PREFERRED,
    RTRIM(TRIM(T1.OFNB1A)) AS PHONE_OFFICE,
    RTRIM(TRIM(T1.MBNB1A)) AS PHONE_MOBILE,

    RTRIM(TRIM(T1.EMIL1A)) AS EMAIL,
    RTRIM(TRIM(T1.GTX11A)) AS GENERAL_TEXT1,
    RTRIM(TRIM(T1.GTX21A)) AS GENERAL_TEXT2,

    CAST(NULL AS VARCHAR(1024)) AS RAPPORT_NOTE

FROM EDUT1F3.T1P1A T1

WHERE
    T1.CONO1A = 'GK'
AND T1.GLCO1A = 'GK'
AND T1.APPL1A = 'SL'
AND T1.DSEQ1A = '000'